name: CD test

on:
  push:
    branches:
    - "feature/update_CD_workflow_include_infrastructure"

jobs:
  deploy-main-environment:
    name: Infrastructure apply
    uses: Nikolajls/TestProject_WebAppCredentials/.github/workflows/CD-start.yml@feature/update_CD_workflow_include_infrastructure
    with:
      terraform-directory: "./infrastructure/"
      azure-terraform-storage-account: "webapptestnikolajls"
      azure-resourcegroup-name: "TestWebApp"
      azure-location-name: "westeurope"
      azure_environment: "Development"
      ASPNETCORE_ENVIRONMENT: "Development"
      Image_repo_server: "ghcr.io"
      Image_repo_user: "USERNAME"
      Image_repo_image_path: "ghcr.io/nikolajls/testproject_webappcredentials:main"
      domain_name_label: "nikolajwebapptest"
      container_name: "webapptest"
      key_vault_name: "nikolajvaf13"
    secrets:
      azure-tenant-id: ${{ secrets.azure_tenant_id }}
      azure-subscription-id: ${{ secrets.app_main_subscription_id }}
      azure-service-principal-id: ${{ secrets.app_main_serviceprincipal_id }}
      azure-service-principal-secret: ${{ secrets.app_main_serviceprincipal_secret }}
      app_authentication_username: ${{ secrets.app_main_username }}
      app_authentication_password: ${{ secrets.app_main_password }}
      Image_repo_user_password: ${{ secrets.app_main_dockerimage_PAT }}

